"""Add attachment fields to announcement

Revision ID: 3f57f0cc9974
Revises: 9d5490e19e86
Create Date: 2026-06-20 22:38:11.269513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f57f0cc9974'
down_revision: Union[str, Sequence[str], None] = '9d5490e19e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('attachment_name', sa.String(length=255), nullable=True))
    op.add_column('announcements', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'attachment_url')
    op.drop_column('announcements', 'attachment_name')
    # ### end Alembic commands ###
