"""Add OpsTicket model

Revision ID: aa6dd66fe53e
Revises: 2ccfef20f4b3
Create Date: 2026-06-17 14:55:18.382009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6dd66fe53e'
down_revision: Union[str, Sequence[str], None] = '2ccfef20f4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_tickets_id'), 'ops_tickets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_tickets_id'), table_name='ops_tickets')
    op.drop_table('ops_tickets')
    # ### end Alembic commands ###
