"""Add file details to CourseMaterial

Revision ID: d17b1b492eb6
Revises: 550a0ad3c1ae
Create Date: 2026-06-22 02:35:51.364686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17b1b492eb6'
down_revision: Union[str, Sequence[str], None] = '550a0ad3c1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('course_materials', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('course_materials', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'file_size')
    op.drop_column('course_materials', 'file_type')
    op.drop_column('course_materials', 'file_name')
    # ### end Alembic commands ###
