"""add assignment task and update submission

Revision ID: f04a98a8b0f7
Revises: d17b1b492eb6
Create Date: 2026-06-22 03:14:52.628510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04a98a8b0f7'
down_revision: Union[str, Sequence[str], None] = 'd17b1b492eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_tasks_id'), 'assignment_tasks', ['id'], unique=False)
    op.add_column('assignments', sa.Column('task_id', sa.Integer(), nullable=False))
    op.add_column('assignments', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('assignments', sa.Column('ai_confidence', sa.String(length=50), nullable=True))
    op.add_column('assignments', sa.Column('final_score', sa.Float(), nullable=True))
    op.add_column('assignments', sa.Column('final_feedback', sa.Text(), nullable=True))
    op.create_index(op.f('ix_assignments_task_id'), 'assignments', ['task_id'], unique=False)
    op.create_foreign_key(None, 'assignments', 'assignment_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_index(op.f('ix_assignments_task_id'), table_name='assignments')
    op.drop_column('assignments', 'final_feedback')
    op.drop_column('assignments', 'final_score')
    op.drop_column('assignments', 'ai_confidence')
    op.drop_column('assignments', 'status')
    op.drop_column('assignments', 'task_id')
    op.drop_index(op.f('ix_assignment_tasks_id'), table_name='assignment_tasks')
    op.drop_table('assignment_tasks')
    # ### end Alembic commands ###
