"""add_EARLY_LEAVE_to_AttendanceStatus

Revision ID: f162003d3927
Revises: 0d8178437000
Create Date: 2026-06-23 02:08:34.525107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f162003d3927'
down_revision: Union[str, Sequence[str], None] = '0d8178437000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'EARLY_LEAVE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
