"""Add file upload to assignments

Revision ID: f64285e94dbd
Revises: f04a98a8b0f7
Create Date: 2026-06-22 03:42:42.371131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64285e94dbd'
down_revision: Union[str, Sequence[str], None] = 'f04a98a8b0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('assignments', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('assignments', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('assignments', sa.Column('file_size', sa.Integer(), nullable=True))
    op.alter_column('assignments', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('assignments', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('assignments', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('assignments', 'file_size')
    op.drop_column('assignments', 'file_type')
    op.drop_column('assignments', 'file_name')
    op.drop_column('assignments', 'file_url')
    # ### end Alembic commands ###
